name: Test build
#MoxIT.ESampling.sln
on: push

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-2019
                             
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
        

    - name: Restore Packages
      run: nuget restore ./ConsoleApp1/ConsoleApp1.sln

    - name: Build Solution
      run: |
        msbuild.exe ./ConsoleApp1/ConsoleApp1.sln /p:platform="Any CPU" /p:configuration="Release"
