name: Test build

on: push

jobs:
  build:
    runs-on: windows-2019
                             
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: dotnet restore
      run: dotnet restore ./ConsoleApp1/ConsoleApp1.sln
    - name: Build
      run: dotnet build ./ConsoleApp1/ConsoleApp1.sln --configuration Release
